{"timestamp": "2024-10-19T19:20:37.529683Z", "level": "INFO", "name": "root", "message": "start_app"}
{"timestamp": "2024-10-19T19:20:52.869982Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0862}
{"timestamp": "2024-10-19T19:20:52.895640Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0082}
{"timestamp": "2024-10-19T19:20:52.897275Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.008}
{"timestamp": "2024-10-19T19:20:52.899099Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0045}
{"timestamp": "2024-10-19T19:20:52.899452Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.004}
{"timestamp": "2024-10-19T19:20:52.899864Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0046}
{"timestamp": "2024-10-19T19:20:52.901573Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0049}
{"timestamp": "2024-10-19T19:20:52.910327Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0065}
{"timestamp": "2024-10-19T19:20:52.911107Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0044}
{"timestamp": "2024-10-19T19:20:53.215108Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.005}
{"timestamp": "2024-10-19T19:20:53.216794Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0082}
{"timestamp": "2024-10-19T19:20:53.217154Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0075}
{"timestamp": "2024-10-19T19:20:53.239727Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0018}
{"timestamp": "2024-10-19T19:20:53.239939Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0018}
{"timestamp": "2024-10-19T19:20:53.248395Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0006}
{"timestamp": "2024-10-19T19:20:53.257085Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0442}
{"timestamp": "2024-10-19T19:20:53.323739Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0014}
{"timestamp": "2024-10-19T19:20:53.900744Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0009}
{"timestamp": "2024-10-19T19:20:57.096882Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0076}
{"timestamp": "2024-10-19T19:21:06.306816Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0351}
{"timestamp": "2024-10-19T19:21:17.138996Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0376}
{"timestamp": "2024-10-19T19:21:19.175322Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0434}
{"timestamp": "2024-10-19T19:21:26.156503Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0515}
{"timestamp": "2024-10-19T19:21:29.829341Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0559}
{"timestamp": "2024-10-19T19:21:30.832186Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0291}
{"timestamp": "2024-10-19T19:21:33.806844Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0406}
{"timestamp": "2024-10-19T19:21:38.867522Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0296}
{"timestamp": "2024-10-19T19:23:15.661188Z", "level": "INFO", "name": "root", "message": "shutdown_app"}
{"timestamp": "2024-10-19T19:23:17.589199Z", "level": "INFO", "name": "root", "message": "start_app"}
{"timestamp": "2024-10-19T19:24:52.282582Z", "level": "INFO", "name": "root", "message": "shutdown_app"}
{"timestamp": "2024-10-19T19:24:54.133108Z", "level": "INFO", "name": "root", "message": "start_app"}
{"timestamp": "2024-10-19T19:26:33.400018Z", "level": "INFO", "name": "root", "message": "shutdown_app"}
{"timestamp": "2024-10-19T19:26:34.979301Z", "level": "INFO", "name": "root", "message": "start_app"}
{"timestamp": "2024-10-19T19:27:06.837529Z", "level": "INFO", "name": "root", "message": "shutdown_app"}
{"timestamp": "2024-10-19T19:27:08.417204Z", "level": "INFO", "name": "root", "message": "start_app"}
{"timestamp": "2024-10-19T19:27:18.108621Z", "level": "INFO", "name": "root", "message": "shutdown_app"}
{"timestamp": "2024-10-19T19:27:19.857799Z", "level": "INFO", "name": "root", "message": "start_app"}
{"timestamp": "2024-10-19T19:27:23.101044Z", "level": "ERROR", "name": "root", "message": "Unknown Exc", "exc_info": "Traceback (most recent call last):\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/app/weather/dao.py\", line 52, in grpc_get_by_loc\n    grpc_client.Weather(WeatherRequest(location=location)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1181, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1006, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {created_time:\"2024-10-20T00:27:23.10012956+05:00\", grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"}\"\n>", "service": "WeatherService"}
{"timestamp": "2024-10-19T19:27:23.153004Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.1144}
{"timestamp": "2024-10-19T19:27:30.033429Z", "level": "ERROR", "name": "root", "message": "Unknown Exc", "exc_info": "Traceback (most recent call last):\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/app/weather/dao.py\", line 52, in grpc_get_by_loc\n    grpc_client.Weather(WeatherRequest(location=location)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1181, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1006, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\", grpc_status:14, created_time:\"2024-10-20T00:27:30.032862933+05:00\"}\"\n>", "service": "WeatherService"}
{"timestamp": "2024-10-19T19:27:30.035761Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0602}
{"timestamp": "2024-10-19T19:27:31.702445Z", "level": "ERROR", "name": "root", "message": "Unknown Exc", "exc_info": "Traceback (most recent call last):\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/app/weather/dao.py\", line 52, in grpc_get_by_loc\n    grpc_client.Weather(WeatherRequest(location=location)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1181, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1006, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\", grpc_status:14, created_time:\"2024-10-20T00:27:31.701952878+05:00\"}\"\n>", "service": "WeatherService"}
{"timestamp": "2024-10-19T19:27:31.704378Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.062}
{"timestamp": "2024-10-19T19:27:33.346994Z", "level": "ERROR", "name": "root", "message": "Unknown Exc", "exc_info": "Traceback (most recent call last):\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/app/weather/dao.py\", line 52, in grpc_get_by_loc\n    grpc_client.Weather(WeatherRequest(location=location)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1181, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1006, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {created_time:\"2024-10-20T00:27:33.345433553+05:00\", grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"}\"\n>", "service": "WeatherService"}
{"timestamp": "2024-10-19T19:27:33.350505Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0722}
{"timestamp": "2024-10-19T19:27:34.966800Z", "level": "ERROR", "name": "root", "message": "Unknown Exc", "exc_info": "Traceback (most recent call last):\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/app/weather/dao.py\", line 52, in grpc_get_by_loc\n    grpc_client.Weather(WeatherRequest(location=location)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1181, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1006, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {created_time:\"2024-10-20T00:27:34.966360152+05:00\", grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"}\"\n>", "service": "WeatherService"}
{"timestamp": "2024-10-19T19:27:34.968800Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0793}
{"timestamp": "2024-10-19T19:27:36.221157Z", "level": "ERROR", "name": "root", "message": "Unknown Exc", "exc_info": "Traceback (most recent call last):\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/app/weather/dao.py\", line 52, in grpc_get_by_loc\n    grpc_client.Weather(WeatherRequest(location=location)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1181, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1006, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {created_time:\"2024-10-20T00:27:36.22067811+05:00\", grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"}\"\n>", "service": "WeatherService"}
{"timestamp": "2024-10-19T19:27:36.222814Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.0768}
{"timestamp": "2024-10-19T19:32:42.307104Z", "level": "INFO", "name": "root", "message": "shutdown_app"}
{"timestamp": "2024-10-19T19:32:44.062475Z", "level": "INFO", "name": "root", "message": "start_app"}
{"timestamp": "2024-10-19T19:32:46.557372Z", "level": "ERROR", "name": "root", "message": "Unknown Exc", "exc_info": "Traceback (most recent call last):\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/app/weather/dao.py\", line 53, in grpc_get_by_loc\n    grpc_client.Weather(WeatherRequest(location=location)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1181, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1006, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\", grpc_status:14, created_time:\"2024-10-20T00:32:46.556589313+05:00\"}\"\n>", "service": "WeatherService"}
{"timestamp": "2024-10-19T19:32:46.608160Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.111}
{"timestamp": "2024-10-19T19:33:21.396446Z", "level": "INFO", "name": "root", "message": "shutdown_app"}
{"timestamp": "2024-10-19T19:33:22.989955Z", "level": "INFO", "name": "root", "message": "start_app"}
{"timestamp": "2024-10-19T19:33:26.867860Z", "level": "ERROR", "name": "root", "message": "Unknown Exc", "exc_info": "Traceback (most recent call last):\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/app/weather/dao.py\", line 53, in grpc_get_by_loc\n    grpc_client.Weather(WeatherRequest(location=location)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1181, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1006, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {created_time:\"2024-10-20T00:33:26.866915593+05:00\", grpc_status:14, grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"}\"\n>", "service": "WeatherService"}
{"timestamp": "2024-10-19T19:33:26.920760Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.1091}
{"timestamp": "2024-10-19T19:33:38.208659Z", "level": "INFO", "name": "root", "message": "shutdown_app"}
{"timestamp": "2024-10-19T19:33:39.895201Z", "level": "INFO", "name": "root", "message": "start_app"}
{"timestamp": "2024-10-19T19:33:41.706989Z", "level": "ERROR", "name": "root", "message": "Unknown Exc", "exc_info": "Traceback (most recent call last):\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/app/weather/dao.py\", line 53, in grpc_get_by_loc\n    grpc_client.Weather(WeatherRequest(location=location)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1181, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/oleg96d/IT/FastAPI/FastAPI/.venv/lib/python3.11/site-packages/grpc/_channel.py\", line 1006, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:10.1.179.64:50051: Failed to connect to remote host: connect: Connection refused (111)\", grpc_status:14, created_time:\"2024-10-20T00:33:41.705708348+05:00\"}\"\n>", "service": "WeatherService"}
{"timestamp": "2024-10-19T19:33:41.759099Z", "level": "INFO", "name": "root", "message": "Request execution time", "process_time": 0.1191}
{"timestamp": "2024-10-19T19:33:51.637868Z", "level": "INFO", "name": "root", "message": "shutdown_app"}
